site_name: Agri-Inn | Documentation

nav:
  - Home: index.md
  - Features: features.md
  - Documentation: docs.md
  - API Reference: api.md
  - Database: database.md
  - AJAX Usage: ajax.md
  - License: license.md
  - About: about.md

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    primary: orange
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search